# Generated by Django 3.2 on 2021-05-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acount',
            fields=[
                ('emial', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('telegram_number', models.CharField(max_length=20)),
            ],
        ),
    ]
