# Generated by Django 3.2 on 2021-05-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_acount_crypto'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='quotes',
            field=models.CharField(default='', max_length=512),
        ),
    ]
