# Generated by Django 3.2 on 2021-05-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_crypto_quotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto',
            name='emial',
        ),
        migrations.AddField(
            model_name='crypto',
            name='email',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='crypto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
